services:
  app:
    #    build: .
    image: demo:v1
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/infra_inventory
      - SESSION_SECRET=your_secret_here
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    ports:
      - "5433:5432" # host:container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=infra_inventory
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d infra_inventory" ]
      interval: 5s
      timeout: 5s
      retries: 5
